// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fachaMotos.Data;

#nullable disable

namespace fachaMotos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250615185908_agregar tablas review reaccion")]
    partial class agregartablasreviewreaccion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fachaMotos.Models.Entities.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("integer");

                    b.Property<double>("CapacidadCombustibleL")
                        .HasColumnType("double precision");

                    b.Property<int>("CilindrajeCC")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PesoKg")
                        .HasColumnType("integer");

                    b.Property<int>("PotenciaHP")
                        .HasColumnType("integer");

                    b.Property<string>("Refrigeracion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TorqueNm")
                        .HasColumnType("double precision");

                    b.Property<string>("Transmision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("medidaNeumaticoDelantero")
                        .HasColumnType("integer");

                    b.Property<int>("medidaNeumaticoTrasero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etiquetas")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.ComentarioBlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaComentario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnLinkes")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("likes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosBlog");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.ComentarioBlogReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComentarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("UserId");

                    b.ToTable("ComentariosBlogReaction");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("integer");

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.ReviewReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewReactions");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ImagenPerfilUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.UserBikeFavorita", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("BikeId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BikeId");

                    b.HasIndex("BikeId");

                    b.ToTable("ListasDeFavoritos");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.ComentarioBlog", b =>
                {
                    b.HasOne("fachaMotos.Models.Entities.Blog", "Blog")
                        .WithMany("Comentarios")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fachaMotos.Models.Entities.User", "Usuario")
                        .WithMany("ComentariosEnBlogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.ComentarioBlogReaction", b =>
                {
                    b.HasOne("fachaMotos.Models.Entities.ComentarioBlog", "Comentario")
                        .WithMany("Reacciones")
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fachaMotos.Models.Entities.User", "Usuario")
                        .WithMany("ComentarioBlogReacciones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.Review", b =>
                {
                    b.HasOne("fachaMotos.Models.Entities.Bike", "Bike")
                        .WithMany("Reviews")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fachaMotos.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("User");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.ReviewReaction", b =>
                {
                    b.HasOne("fachaMotos.Models.Entities.Review", "Review")
                        .WithMany("Reacciones")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fachaMotos.Models.Entities.User", "Usuario")
                        .WithMany("ReviewReacciones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.UserBikeFavorita", b =>
                {
                    b.HasOne("fachaMotos.Models.Entities.Bike", "Bike")
                        .WithMany("UsuariosQueLaTienenComoFavorita")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fachaMotos.Models.Entities.User", "User")
                        .WithMany("MotosFavoritas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("User");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.Bike", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("UsuariosQueLaTienenComoFavorita");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.Blog", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.ComentarioBlog", b =>
                {
                    b.Navigation("Reacciones");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.Review", b =>
                {
                    b.Navigation("Reacciones");
                });

            modelBuilder.Entity("fachaMotos.Models.Entities.User", b =>
                {
                    b.Navigation("ComentarioBlogReacciones");

                    b.Navigation("ComentariosEnBlogs");

                    b.Navigation("MotosFavoritas");

                    b.Navigation("ReviewReacciones");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
